import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import path from 'node:path'
import { fileURLToPath, URL } from 'node:url'

import { defineConfig, type Plugin } from 'vite-plus'
import vue from '@vitejs/plugin-vue'
import vueDevTools from 'vite-plugin-vue-devtools'

const projectRoot = fileURLToPath(new URL('.', import.meta.url))
const stockfishBinDir = path.join(projectRoot, 'node_modules', 'stockfish', 'bin')
const ENGINE_FILES = ['stockfish-18-lite-single.js', 'stockfish-18-lite-single.wasm']

function stockfishPlugin(): Plugin {
  return {
    name: 'stockfish-engines',
    configResolved() {
      const destDir = path.join(projectRoot, 'public', 'engines')
      mkdirSync(destDir, { recursive: true })
      for (const f of ENGINE_FILES) {
        const dest = path.join(destDir, f)
        if (!existsSync(dest)) {
          console.log(`[stockfish] Copying ${f} to public/engines/ …`)
          copyFileSync(path.join(stockfishBinDir, f), dest)
        }
      }
    },
  }
}

// exercises.json (frontend/public/exercises.json, not committed — see .gitignore) is
// periodically refreshed by backend/scripts/export_puzzles.mjs. It's served under a
// content-hashed filename plus a tiny, always-revalidated manifest so the frontend can
// point at it with an aggressive immutable Cache-Control while still picking up a new
// export the next time the app loads (see public/_headers and src/stores/exercises.ts).
function exercisesCatalogPlugin(): Plugin {
  return {
    name: 'exercises-catalog',
    closeBundle() {
      const outDir = path.join(projectRoot, 'dist')
      const plainPath = path.join(outDir, 'exercises.json')
      if (!existsSync(plainPath)) {
        console.warn(
          '[exercises-catalog] dist/exercises.json not found, skipping — copy ' +
            'frontend/public/exercises.json in place before building for production.',
        )
        return
      }

      const contents = readFileSync(plainPath)
      const hash = createHash('sha256').update(contents).digest('hex').slice(0, 10)

      const dataDir = path.join(outDir, 'data')
      mkdirSync(dataDir, { recursive: true })
      const hashedFilename = `exercises-${hash}.json`
      writeFileSync(path.join(dataDir, hashedFilename), contents)
      rmSync(plainPath)

      writeFileSync(
        path.join(outDir, 'exercises-manifest.json'),
        JSON.stringify({ file: `/data/${hashedFilename}` }),
      )
      console.log(`[exercises-catalog] Wrote /data/${hashedFilename} + exercises-manifest.json`)
    },
    configureServer(server) {
      server.middlewares.use('/exercises-manifest.json', (_req, res) => {
        res.setHeader('Content-Type', 'application/json')
        res.end(JSON.stringify({ file: '/exercises.json' }))
      })
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  fmt: {
    semi: false,
    singleQuote: true,
  },
  lint: {
    plugins: ['eslint', 'typescript', 'unicorn', 'oxc', 'vue'],
    categories: {
      correctness: 'error',
    },
    env: {
      browser: true,
      builtin: true,
    },
    ignorePatterns: [
      '**/dist/**',
      '**/dist-ssr/**',
      '**/coverage/**',
      // Generated by backend/scripts/db.sh types — regenerated, never hand-edited
      'src/types/database.ts',
    ],
    rules: {
      'no-array-constructor': 'error',
      'typescript/ban-ts-comment': 'error',
      'typescript/no-empty-object-type': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'vite-plus/prefer-vite-plus-imports': 'error',
    },
    overrides: [
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts', '**/*.vue'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-var': 'error',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
  },
  plugins: [
    stockfishPlugin(),
    exercisesCatalogPlugin(),
    vue({
      template: {
        compilerOptions: { isCustomElement: (tag) => ['piece', 'cg-board'].includes(tag) },
      },
    }),
    vueDevTools(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
})
