// The request handlers behind the link-preview routes (see worker.ts). A shared puzzle
// URL (/train?puzzle=<fen>) is rendered by the SPA in the browser, but a crawler only
// ever sees index.html — so these inject Open Graph tags derived from the fen and serve
// the position as a PNG. Everything else on the site is untouched static assets.

import { decodeSprites, renderPositionPng, type BoardSprites } from './boardImage'
import { parseFen } from './fen'
import { buildPreviewTags, injectPreviewTags, PUZZLE_QUERY_PARAM } from './preview'

export interface PreviewEnv {
  ASSETS: Fetcher
}

// Generated by scripts/build-og-sprites.mjs; fetched through the assets binding rather
// than bundled into the script, which keeps a megabyte of pixels out of the Worker.
const SPRITE_ASSET_PATH = '/og-sprites.bin'

const IMMUTABLE_CACHE_CONTROL = 'public, max-age=31536000, immutable'

// Also set in public/_headers and vite.config.ts: the multi-threaded Stockfish build
// needs SharedArrayBuffer, which only exists in a cross-origin isolated context. Applied
// here explicitly so a rewritten document cannot lose them.
const CROSS_ORIGIN_ISOLATION_HEADERS: [string, string][] = [
  ['Cross-Origin-Opener-Policy', 'same-origin'],
  ['Cross-Origin-Embedder-Policy', 'require-corp'],
]

// Inflating and slicing up the sprite blob takes long enough to be worth keeping for the
// life of the isolate, but not so long that it needs doing before the first request.
let cachedSprites: Promise<BoardSprites> | undefined

function loadSprites(env: PreviewEnv, pageUrl: URL): Promise<BoardSprites> {
  cachedSprites ??= fetchSprites(env, pageUrl).catch((error: unknown) => {
    // Never let one failed fetch poison every later request in this isolate.
    cachedSprites = undefined
    throw error
  })
  return cachedSprites
}

async function fetchSprites(env: PreviewEnv, pageUrl: URL): Promise<BoardSprites> {
  const response = await env.ASSETS.fetch(new URL(SPRITE_ASSET_PATH, pageUrl))
  if (!response.ok) throw new Error(`${SPRITE_ASSET_PATH} is missing from the deployment`)
  return await decodeSprites(await response.arrayBuffer())
}

export async function renderBoardImage(
  request: Request,
  url: URL,
  env: PreviewEnv,
  context: ExecutionContext,
): Promise<Response> {
  const cacheKey = new Request(url.toString(), { method: 'GET' })
  const cached = await caches.default.match(cacheKey)
  if (cached) return request.method === 'HEAD' ? new Response(null, cached) : cached

  const position = parseFen(url.searchParams.get(PUZZLE_QUERY_PARAM) ?? '')
  if (!position) return new Response('Not a position', { status: 404 })

  const sprites = await loadSprites(env, url)
  const response = new Response(renderPositionPng(sprites, position), {
    headers: {
      'Content-Type': 'image/png',
      'Cache-Control': IMMUTABLE_CACHE_CONTROL,
      // The document is cross-origin isolated; without this the image could not be
      // embedded in the app itself, only linked to.
      'Cross-Origin-Resource-Policy': 'cross-origin',
    },
  })
  context.waitUntil(caches.default.put(cacheKey, response.clone()))
  return request.method === 'HEAD' ? new Response(null, response) : response
}

export async function renderPreviewDocument(
  request: Request,
  url: URL,
  env: PreviewEnv,
): Promise<Response> {
  // The app's own shell, exactly as the assets would have served it for this route.
  const assetResponse = await env.ASSETS.fetch(new URL('/index.html', url))

  const rawFen = url.searchParams.get(PUZZLE_QUERY_PARAM)
  const position = rawFen === null ? null : parseFen(rawFen)
  if (!position || rawFen === null || !assetResponse.ok) return assetResponse

  const sprites = await loadSprites(env, url)
  const html = injectPreviewTags(
    await assetResponse.text(),
    buildPreviewTags({ position, pageUrl: url, rawFen, boardSize: sprites.boardSize }),
  )

  const headers = new Headers(assetResponse.headers)
  // The rewrite invalidates both: the body is a different length and no longer the
  // asset the entity tag identifies.
  headers.delete('Content-Length')
  headers.delete('ETag')
  for (const [name, value] of CROSS_ORIGIN_ISOLATION_HEADERS) headers.set(name, value)

  return new Response(request.method === 'HEAD' ? null : html, {
    status: assetResponse.status,
    headers,
  })
}
